name: Check Security Patches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC

jobs:
  check_patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Execute SSM Command to Check Patches
        id: check_patches
        run: |
          aws ssm send-command \
            --document-name "AWS-RunPowerShellScript" \
            --targets "Key=instanceIds,Values=i-0441ba81fb9000eec" \
            --parameters commands=["powershell -File C:\\path\\to\\your\\script\\find_and_upload_patches.ps1 -BucketArn arn:aws:s3:::sycdel-test2 -AWSRegion us-east-1"] \
            --comment "Check for available security patches and upload to S3" \
            --output text

      - name: Fetch Patch List from S3
        run: |
          aws s3 cp s3://sycdel-test2/i-0441ba81fb9000eec/security_patches.txt ./security_patches.txt --region us-east-1
          cat ./security_patches.txt
