name: Check Security Patches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC

jobs:
  check_patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo apt-get install -y oathtool
          sudo apt-get install -y pwsh

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Execute script with MFA
        run: |
          chmod +x run_with_mfa.sh
          ./run_with_mfa.sh
        env:
          MFA_SECRET: ${{ secrets.MFA_SECRET }}
