# This is a basic workflow that is manually triggered

name: Manual workflow

name: Security Patch Deployment

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  approve_and_invoke_lambda:
    runs-on: ubuntu-latest
    environment: patch-approval # Protected environment for manual approval

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Wait for Approval
        id: wait_for_approval
        run: echo "Awaiting manual approval in the 'patch-approval' environment."

      - name: Invoke Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          # Specify the Lambda function name
          LAMBDA_FUNCTION_NAME="apply-security-patches"

          # Trigger the Lambda function
          echo "Invoking Lambda function..."
          aws lambda invoke \
            --function-name $LAMBDA_FUNCTION_NAME \
            --payload '{}' \
            output.json

          # Display the Lambda function output
          echo "Lambda function response:"
          cat output.json
