name: Invoke Lambda to Install Security Patches

on:
  push:
    branches:
      - main
    paths:
      - instance_patches.txt

jobs:
  invoke_lambda_patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl jq
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_session_token $AWS_SESSION_TOKEN
          aws configure set region $AWS_REGION

      - name: Invoke Lambda Function to Install Security Patches
        run: |
          echo "Invoking Lambda function: installSecurityPatches..."
          aws lambda invoke \
            --function-name installSecurityPatches \
            --region us-east-1 \
            response.json

          echo "Lambda invoked. Response:"
          cat response.json

      - name: Fetch Patch Status from S3
        run: |
          echo "Fetching patch install summary from S3..."
          aws s3 cp s3://your-s3-bucket-name/patch_status_summary.txt patch_status_summary.txt
          cat patch_status_summary.txt
