name: Post-Merge Patch Deploy

on:
  push:
    branches:
      - main
    paths:
      - instance_patches.txt

jobs:
  trigger_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Copy instance_patches.txt to S3 (optional)
        run: |
          aws s3 cp instance_patches.txt s3://your-patch-bucket/instance_patches.txt

      - name: Invoke Lambda to run patch installation
        run: |
          aws lambda invoke \
            --function-name installSecurityPatches \
            --payload file://instance_patches.txt \
            output.json

      - name: Upload patch results to repo (optional)
        run: |
          PATCH_RESULT_FILE="patch_results.txt"
          if [ -f "$PATCH_RESULT_FILE" ]; then
            echo "Uploading patch result..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b patch-status-update
            cp "$PATCH_RESULT_FILE" .
            git add patch_results.txt
            git commit -m "Update patch results"
            git push origin patch-status-update
          fi

      - name: Create PR to merge patch results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update patch results
          branch: patch-status-update
          title: 'Patch Results Update'
          body: 'This PR contains the output of the patch installation script.'
