name: Check Security Patches on Red Hat and Store in S3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run every Monday at midnight UTC

jobs:
  check_security_patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Execute SSM Command to Check Patches and Upload to S3
        run: |
          aws ssm send-command \
            --instance-ids i-008e8f3c90e3bee1a \
            --document-name "AWS-RunShellScript" \
            --comment "Check critical and important security patches and upload to S3" \
            --parameters 'commands=["/path/to/check_and_upload_patches.sh"]' \
            --output text \
            --region ${{ secrets.AWS_REGION }}
