- name: Run Security Patch Script via SSM
  env:
    AWS_PROFILE: temp-mfa
    S3_BUCKET: testpatchscript
  run: |
    # Define instance ID and result file path
    INSTANCE_ID="i-008e8f3c90e3bee1a"
    RESULT_FILE="/usr/bin/security_patches.txt"

    # Run the script on the EC2 instance with elevated privileges
    echo "Running patch check script on EC2 with sudo..."
    COMMAND_ID=$(aws ssm send-command \
      --instance-ids $INSTANCE_ID \
      --document-name "AWS-RunShellScript" \
      --comment "Check critical and important security patches and upload results to S3" \
      --parameters 'commands=[
        "sudo /usr/bin/check_security_patches.sh",
        "sudo chmod 644 /usr/bin/security_patches.txt"
      ]' \
      --query "Command.CommandId" \
      --output text)

    # Wait for the command to complete
    echo "Waiting for command to complete..."
    aws ssm wait command-executed --command-id $COMMAND_ID --instance-id $INSTANCE_ID

    # Verify the result file exists
    echo "Verifying if the result file exists on the EC2 instance..."
    FILE_EXISTS=$(aws ssm send-command \
      --instance-ids $INSTANCE_ID \
      --document-name "AWS-RunShellScript" \
      --parameters 'commands=["if [ -f /usr/bin/security_patches.txt ]; then echo File exists; else echo File not found; fi"]' \
      --query "Command.CommandId" \
      --output text)
    aws ssm wait command-executed --command-id $FILE_EXISTS --instance-id $INSTANCE_ID
    FILE_STATUS=$(aws ssm get-command-invocation \
      --command-id $FILE_EXISTS \
      --instance-id $INSTANCE_ID \
      --query "StandardOutputContent" \
      --output text)

    if [[ "$FILE_STATUS" != "File exists" ]]; then
      echo "Error: The result file does not exist on the EC2 instance."
      exit 1
    fi

    # Print the contents of the result file for debugging
    echo "Fetching result file contents..."
    FILE_CONTENTS=$(aws ssm send-command \
      --instance-ids $INSTANCE_ID \
      --document-name "AWS-RunShellScript" \
      --parameters 'commands=["sudo cat /usr/bin/security_patches.txt"]' \
      --query "Command.CommandId" \
      --output text)
    aws ssm wait command-executed --command-id $FILE_CONTENTS --instance-id $INSTANCE_ID
    aws ssm get-command-invocation \
      --command-id $FILE_CONTENTS \
      --instance-id $INSTANCE_ID \
      --query "StandardOutputContent" \
      --output text

    # Upload the result file to S3
    echo "Uploading result file to S3..."
    aws s3 cp $RESULT_FILE s3://$S3_BUCKET/$INSTANCE_ID/security_patches.txt --region us-east-1

    echo "Security patches report uploaded to S3 successfully."
