name: Upload Patch Files and Python Installer to EC2

on:
  workflow_dispatch:

jobs:
  upload_patch_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y oathtool jq unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Generate MFA Code and Get Temporary AWS Credentials
        id: mfa_creds
        env:
          MFA_SECRET: ${{ secrets.MFA_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MFA_SERIAL_ARN: arn:aws:iam::472598590798:mfa/TESTGIT1
          AWS_DEFAULT_REGION: us-east-1
        run: |
          MFA_CODE=$(oathtool --base32 --totp "$MFA_SECRET")
          TEMP_CREDS=$(aws sts get-session-token \
            --serial-number $MFA_SERIAL_ARN \
            --token-code $MFA_CODE \
            --duration-seconds 3600 \
            --output json)
          echo "AWS_ACCESS_KEY_ID=$(echo $TEMP_CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $TEMP_CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $TEMP_CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Configure AWS CLI with Temporary Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile temp-mfa
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile temp-mfa
          aws configure set aws_session_token $AWS_SESSION_TOKEN --profile temp-mfa
          aws configure set region us-east-1 --profile temp-mfa

      - name: Upload Patch Files and Python Installer to EC2
        env:
          AWS_PROFILE: temp-mfa
        run: |
          for INSTANCE_ID in $(cat instance.txt); do
            echo "📦 Uploading to instance: $INSTANCE_ID"
            PATCH_FILE="${INSTANCE_ID}_patches.txt"

            if [[ ! -f "$PATCH_FILE" || ! -f install_security_patches.py ]]; then
              echo "❌ Required file missing: $PATCH_FILE or install_security_patches.py"
              continue
            fi

            echo "📝 Uploading patch list and Python installer..."

            # Upload PATCH file
            aws ssm send-command \
              --region us-east-1 \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Upload patch file" \
              --parameters "commands=[
                'mkdir -p /usr/bin/patchscript',
                'cat << EOF > /usr/bin/patchscript/${PATCH_FILE}',
                '$(cat "${PATCH_FILE}")',
                'EOF'
              ]" \
              --output text

            # Upload Python script
            aws ssm send-command \
              --region us-east-1 \
              --instance-ids "$INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Upload Python patch installer" \
              --parameters "commands=[
                'cat << EOF > /usr/bin/patchscript/install_security_patches.py',
                '$(cat install_security_patches.py)',
                'EOF',
                'chmod +x /usr/bin/patchscript/install_security_patches.py'
              ]" \
              --output text
          done
